/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesEcommerceRouteImport } from './routes/services.ecommerce'
import { Route as ServicesBusinessWebsitesRouteImport } from './routes/services.business-websites'
import { Route as ServicesBookingSystemsRouteImport } from './routes/services.booking-systems'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEcommerceRoute = ServicesEcommerceRouteImport.update({
  id: '/services/ecommerce',
  path: '/services/ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBusinessWebsitesRoute =
  ServicesBusinessWebsitesRouteImport.update({
    id: '/services/business-websites',
    path: '/services/business-websites',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesBookingSystemsRoute = ServicesBookingSystemsRouteImport.update({
  id: '/services/booking-systems',
  path: '/services/booking-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/process': typeof ProcessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/services/booking-systems': typeof ServicesBookingSystemsRoute
  '/services/business-websites': typeof ServicesBusinessWebsitesRoute
  '/services/ecommerce': typeof ServicesEcommerceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/process': typeof ProcessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/services/booking-systems': typeof ServicesBookingSystemsRoute
  '/services/business-websites': typeof ServicesBusinessWebsitesRoute
  '/services/ecommerce': typeof ServicesEcommerceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/process': typeof ProcessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/services/booking-systems': typeof ServicesBookingSystemsRoute
  '/services/business-websites': typeof ServicesBusinessWebsitesRoute
  '/services/ecommerce': typeof ServicesEcommerceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/process'
    | '/sitemap.xml'
    | '/work'
    | '/admin'
    | '/services/booking-systems'
    | '/services/business-websites'
    | '/services/ecommerce'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/process'
    | '/sitemap.xml'
    | '/work'
    | '/admin'
    | '/services/booking-systems'
    | '/services/business-websites'
    | '/services/ecommerce'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/process'
    | '/sitemap.xml'
    | '/work'
    | '/_authenticated/admin'
    | '/services/booking-systems'
    | '/services/business-websites'
    | '/services/ecommerce'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ProcessRoute: typeof ProcessRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkRoute: typeof WorkRoute
  ServicesBookingSystemsRoute: typeof ServicesBookingSystemsRoute
  ServicesBusinessWebsitesRoute: typeof ServicesBusinessWebsitesRoute
  ServicesEcommerceRoute: typeof ServicesEcommerceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ecommerce': {
      id: '/services/ecommerce'
      path: '/services/ecommerce'
      fullPath: '/services/ecommerce'
      preLoaderRoute: typeof ServicesEcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/business-websites': {
      id: '/services/business-websites'
      path: '/services/business-websites'
      fullPath: '/services/business-websites'
      preLoaderRoute: typeof ServicesBusinessWebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/booking-systems': {
      id: '/services/booking-systems'
      path: '/services/booking-systems'
      fullPath: '/services/booking-systems'
      preLoaderRoute: typeof ServicesBookingSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ProcessRoute: ProcessRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkRoute: WorkRoute,
  ServicesBookingSystemsRoute: ServicesBookingSystemsRoute,
  ServicesBusinessWebsitesRoute: ServicesBusinessWebsitesRoute,
  ServicesEcommerceRoute: ServicesEcommerceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
