/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesEcommerceRouteImport } from './routes/services.ecommerce'
import { Route as ServicesBusinessWebsitesRouteImport } from './routes/services.business-websites'
import { Route as ServicesBookingSystemsRouteImport } from './routes/services.booking-systems'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEcommerceRoute = ServicesEcommerceRouteImport.update({
  id: '/services/ecommerce',
  path: '/services/ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBusinessWebsitesRoute =
  ServicesBusinessWebsitesRouteImport.update({
    id: '/services/business-websites',
    path: '/services/business-websites',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesBookingSystemsRoute = ServicesBookingSystemsRouteImport.update({
  id: '/services/booking-systems',
  path: '/services/booking-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/services/booking-systems': typeof ServicesBookingSystemsRoute
  '/services/business-websites': typeof ServicesBusinessWebsitesRoute
  '/services/ecommerce': typeof ServicesEcommerceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/services/booking-systems': typeof ServicesBookingSystemsRoute
  '/services/business-websites': typeof ServicesBusinessWebsitesRoute
  '/services/ecommerce': typeof ServicesEcommerceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/services/booking-systems': typeof ServicesBookingSystemsRoute
  '/services/business-websites': typeof ServicesBusinessWebsitesRoute
  '/services/ecommerce': typeof ServicesEcommerceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/services/booking-systems'
    | '/services/business-websites'
    | '/services/ecommerce'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/services/booking-systems'
    | '/services/business-websites'
    | '/services/ecommerce'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/services/booking-systems'
    | '/services/business-websites'
    | '/services/ecommerce'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ServicesBookingSystemsRoute: typeof ServicesBookingSystemsRoute
  ServicesBusinessWebsitesRoute: typeof ServicesBusinessWebsitesRoute
  ServicesEcommerceRoute: typeof ServicesEcommerceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ecommerce': {
      id: '/services/ecommerce'
      path: '/services/ecommerce'
      fullPath: '/services/ecommerce'
      preLoaderRoute: typeof ServicesEcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/business-websites': {
      id: '/services/business-websites'
      path: '/services/business-websites'
      fullPath: '/services/business-websites'
      preLoaderRoute: typeof ServicesBusinessWebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/booking-systems': {
      id: '/services/booking-systems'
      path: '/services/booking-systems'
      fullPath: '/services/booking-systems'
      preLoaderRoute: typeof ServicesBookingSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ServicesBookingSystemsRoute: ServicesBookingSystemsRoute,
  ServicesBusinessWebsitesRoute: ServicesBusinessWebsitesRoute,
  ServicesEcommerceRoute: ServicesEcommerceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
